services:
  - type: web
    name: jessie-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
      - key: GOOGLE_API_KEY
        sync: false
